/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sport;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sun.reflect.LangReflectAccess;

/**
 *

 */
public class AddCoaches extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement pst =null;
    ResultSet ra =null;
    /**
     * Creates new form AddStudent
     */
    public AddCoaches() {
        initComponents();
        Idbox.setEditable(false);
 
        conn =Dbconnect.connect();
        tableload();
    }
 public void tableload()
    {
        try{
        String sql ="Select Coach_Name , Sport from coach";
        pst = conn.prepareStatement(sql);
         ResultSet  rs = pst.executeQuery();
        jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        
        
        }catch (Exception e){
        
        }
    }
 public void getTable( ){
        int r = jTable1.getSelectedRow();
        
        String  cid= jTable1.getValueAt(r,0).toString();
               
        String sql = "SElect * from coach where Coach_Name ='"+cid+"'";
       try {
           PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs= pst.executeQuery();
           while (rs.next()) {
                String name =rs.getString("Coach_Name");
                String sport = rs.getString("Sport");
                String address = rs.getString("Address");
                int cont = rs.getInt("Contact_No");
                String coon = Integer.toString(cont);
                int ciid = rs.getInt("Coach_Id");
                String coid =Integer.toString(ciid);
                Idbox.setText(coid);
                Namebox.setText(name);
                Conbox.setText(coon);
                addressbox.setText(address);
                
                  SportCombo1.setSelectedItem(sport);
                
               
           }
         
     } catch (Exception e) {
     }
        
        
        
        
        
        
//       String name = jTable1.getValueAt(r,1).toString();
//       String sport = jTable1.getValueAt(r,2).toString();
//       String address = jTable1.getValueAt(r,3).toString();
//                                       
//        SportCombo.setSelectedItem(game);
//        Datebox.setText(date);
//        textBox.setText(description);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Idbox = new javax.swing.JTextField();
        Namebox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SportCombo1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addressbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Conbox = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Sport"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameboxActionPerformed(evt);
            }
        });
        Namebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameboxKeyPressed(evt);
            }
        });

        jLabel1.setText("Coach ID");

        jLabel2.setText(" Name");

        jLabel5.setText("Sport");

        SportCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cricket", "Volleyball", "Football", "Swimming", "Badminton" }));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Add Coaches");

        jLabel3.setText("Address");

        jLabel4.setText("Contact No");

        Conbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ConboxKeyPressed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/image/WhatsApp Image 2017-08-20 at 21.00.30.jpeg"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(SportCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Idbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Namebox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Conbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addressbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Idbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Namebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(Conbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(addressbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(SportCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addGap(13, 13, 13))
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       // int x = JOptionPane.showConfirmDialog(null,"Do you want to Add a coach");
        //
        String Coach_ID = Idbox.getText();
        String Name = Namebox.getText();
        String Contact_No = Conbox.getText();
        
        String Address = addressbox.getText();
        String Sport = SportCombo1.getSelectedItem() .toString();

        
        
        
        
        
        if("".equals(Coach_ID) || "".equals(Name) || "".equals(Coach_ID) || "".equals(Address) || "".equals(Sport) ){JOptionPane.showMessageDialog(null, "Enter all values");}
           
        else{
        try{
            
        int x = JOptionPane.showConfirmDialog(null,"Do you want to Add a coach");
         if(x==0){   
        String q = "INSERT INTO coach (Coach_Name,Contact_No,Address,Sport) values ('"+Name+"', '"+Contact_No+"', '"+Address+"', '"+Sport+"')";
        pst = conn.prepareStatement(q);
        pst.execute();}
        }catch (Exception e){
        
        }
        tableload();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
            String Coach_ID = Idbox.getText();
            String Name = Namebox.getText();
            String Contact_No = Conbox.getText();
        
            String Address = addressbox.getText();
            String Sport = SportCombo1.getSelectedItem() .toString();
        
       if(  "".equals(Coach_ID)||"".equals(Name)||"".equals(Contact_No)||"".equals(Address)||"".equals(Sport)){
       JOptionPane.showMessageDialog(null, "Enter the all values");
       }     
       else{    
        int x = JOptionPane.showConfirmDialog(null,"Do you want to update");
        if(x==0){
        
//            String Coach_ID = Idbox.getText();
//            String Name = Namebox.getText();
//            String Contact_No = Conbox.getText();
//        
//            String Address = addressbox.getText();
//            String Sport = SportCombo1.getSelectedItem() .toString();
            
            String sql = "UPDATE coach SET Coach_Name = '"+ Name +"' ,Contact_No = '"+ Contact_No +"', Address = '"+ Address +"', Sport = '"+ Sport +"' where Coach_id = '"+ Coach_ID+"'";
            try{
                pst =conn.prepareStatement(sql);
                pst.execute();
                
                tableload();
            }catch(Exception e){
            }
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      getTable();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         int x = JOptionPane.showConfirmDialog(null,"Do you want to delete coach record ");
        if(x==0){
           
            String cid = Idbox.getText();
            int c=Integer.parseInt(cid);
            
            String sql = "DELETE from coach Where Coach_Id ="+ c ;
            try{
                pst =conn.prepareStatement(sql);
                pst.execute();
                tableload();
                
                tableload();
            }catch(SQLException e){
            }
        // TODO add your handling code here:
        
    }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
            
       
    }//GEN-LAST:event_jButton1KeyPressed

    private void ConboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConboxKeyPressed
      if(evt.getKeyCode()>=KeyEvent.VK_0 && evt.getKeyCode()<=KeyEvent.VK_9 || evt.getKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getKeyCode()==KeyEvent.VK_DELETE || evt.getKeyCode()==KeyEvent.VK_LEFT || evt.getKeyCode()==KeyEvent.VK_RIGHT)
        {
            if(Conbox.getText().length()<10 || evt.getKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getKeyCode()==KeyEvent.VK_DELETE || evt.getKeyCode()==KeyEvent.VK_LEFT || evt.getKeyCode()==KeyEvent.VK_RIGHT)
            {
                Conbox.setEditable(true);
                Conbox.setBackground(Color.white);
                
                
            }
            else
            {
                Conbox.setEditable(false);
                Conbox.setBackground(Color.white);
                
            }
        }
        else
        {
            Conbox.setEditable(false);
            Conbox.setBackground(Color.red);
            
        }
    }//GEN-LAST:event_ConboxKeyPressed

    private void NameboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameboxKeyPressed
        char key = evt.getKeyChar();
        
       if ((key>=evt.VK_A || key>=evt.VK_Z) || key == KeyEvent.VK_BACK_SPACE){
           
           Namebox.setEditable(true);
           Namebox.setBackground(Color.WHITE);
       }else
       {
         Namebox.setEditable(false);
           Namebox.setBackground(Color.red);
       
       }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_NameboxKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Sports A3 =new Sports ();
        A3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private boolean isName(String name){
        //check if the given striing contains onl letters and spaces
            for(int x=0;x<name.length();x++){
                if(!(Character.isLetter(name.charAt(x)) || Character.isWhitespace(name.charAt(x)))){
                    return false;
                }
            }
            return true;
    }
    
    private boolean addressbox_validate(){
         if (addressbox.getText().isEmpty()){
             //addressbox.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.red));
             return false;
        }else{
           // addressbox.setBorder(BorderFactory.createMatteBorder(2,2,2,2,Color.green));
            return true;
           
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCoaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCoaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCoaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCoaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCoaches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Conbox;
    private javax.swing.JTextField Idbox;
    private javax.swing.JTextField Namebox;
    private javax.swing.JComboBox<String> SportCombo1;
    private javax.swing.JTextField addressbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
