/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import mail.student_mail;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import mycode.dbconnect1;
import net.proteanit.sql.DbUtils;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.table.TableModel;

/**
 *
 * @author SURESH_UDAYA
 */
public class Add_Payment_Details extends javax.swing.JInternalFrame {

    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Add_Payment_Details() {
        initComponents();
        
        con =dbconnect1.connect();
        
        tableload();
    }
    public void reset(){
    
        SID.setText(null);
        amount.setText(null);
        fees.setText(null);
        term.setSelectedItem(null);
        clz.setSelectedItem(null);
        pid_search.setText(null);
    
    }
    
    
    
    
    
    
    public void tableload(){
    
       try{
        String sql = "SELECT payment_id,student_ID,class,term,paid_amount,late_fees FROM student_payment";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        table.setModel(DbUtils.resultSetToTableModel(rs));
        
       }
       catch(Exception e){
           System.out.println("table load error");
       }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        fees = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        sid = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        search = new javax.swing.JButton();
        pid_search = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        term = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        clz = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        SID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(new javax.swing.border.MatteBorder(null));
        setPreferredSize(new java.awt.Dimension(2048, 2048));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 67, 57, -1));

        jLabel2.setText("Payment_amount");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 92, 23));

        jLabel3.setText("Due_fees");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 92, 19));
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 90, -1));
        getContentPane().add(fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 90, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 73, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 440, 220));

        sid.setText("Payment_ID");
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        pid.setText("ID");
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 20, -1));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));
        getContentPane().add(pid_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 100, -1));

        jLabel4.setText("Payment_ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 60, 20));

        jLabel5.setText("Term");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 30));

        term.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        getContentPane().add(term, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 100, 40, -1));

        jLabel6.setText("class");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, -1));

        clz.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        getContentPane().add(clz, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 40, -1));

        jLabel8.setText("SID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, -1));
        getContentPane().add(SID, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 10, 70, -1));

        jButton3.setText("Send Payment Details Through E-mail");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 250, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String sid = SID.getText();
        String Amount = amount.getText();
        String Fees = fees.getText();
        String Sem = term.getSelectedItem().toString();
        String Clz = clz.getSelectedItem().toString();
        
       try{
            String q = "INSERT INTO student_payment(student_ID,class,term,paid_amount,late_fees)values('"+sid+"','"+Clz+"','"+Sem+"','"+Amount+"','"+Fees+"')";
            
            pst = con.prepareStatement(q);
            pst.execute();
            tableload();
            reset();
       }
       catch(Exception e){
           System.out.println("db add error");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
        int r = table.getSelectedRow();
        
        String Pid = table.getValueAt(r, 0).toString();
        String sid = table.getValueAt(r, 1).toString();
        String Clz = table.getValueAt(r, 2).toString();
        String Sem = table.getValueAt(r, 3).toString();
        String Amount = table.getValueAt(r, 4).toString();
        String late_fee = table.getValueAt(r, 5).toString();
        
        
       
        amount.setText(Amount);
        fees.setText(late_fee);
        pid.setText(Pid);
        SID.setText(sid);
        clz.setSelectedItem(Clz);
        term.setSelectedItem(Sem);
        
    }//GEN-LAST:event_tableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null,"Do you really want to update ? ");
        if(x==0){
        
            String payID = pid.getText();
            String Sid = SID.getText();
            String Amount =amount.getText();
            String late_fee = fees.getText();
            String Sem = term.getSelectedItem().toString();
            String Clz = clz.getSelectedItem().toString();
             
            try{
                String sql = "UPDATE student_payment SET student_ID='"+Sid+"',class='"+Clz+"',term='"+Sem+"',paid_amount='"+Amount+"',late_fees='"+late_fee+"' where payment_id='"+payID+"'";
                pst = con.prepareStatement(sql);
                pst.execute();
                reset();
                tableload();
            }
            catch(Exception e){
                System.out.println("update error");
            }
            
        }
     
        
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        
        
        int d=JOptionPane.showConfirmDialog(null,"Do you really want to Delete this ? ");
        
        if(d==0){
        
            String pID = pid.getText();
            
            
            String sql ="DELETE FROM student_payment WHERE payment_id='"+pID+"'";
            try{
                pst = con.prepareStatement(sql);
                pst.execute();
                tableload();
            }
            catch(Exception e){
                System.out.println("delete error ");
            }
        
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
     
        String Pid= pid_search.getText();
        try{
            
            String sql="SELECT payment_id,student_ID,paid_amount,late_fees FROM student_payment WHERE payment_id ='"+Pid+"' ";
        
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
                    
            table.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e){
            System.out.println(e);
        }
        
        
        
    }//GEN-LAST:event_searchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
       
        
         student_mail ml = new student_mail();
         ml.setVisible(true);
         this.dispose();
        
         
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        reset();
        tableload();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SID;
    private javax.swing.JTextField amount;
    private javax.swing.JComboBox clz;
    private javax.swing.JButton delete;
    private javax.swing.JTextField fees;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pid;
    private javax.swing.JTextField pid_search;
    private javax.swing.JButton search;
    private javax.swing.JLabel sid;
    private javax.swing.JTable table;
    private javax.swing.JComboBox term;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
