/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calendar1.Timetable;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DELL
 */
public class timetableStu extends javax.swing.JFrame {

    /**
     * Creates new form timetableStu
     */
    public timetableStu() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"7.30-8.30", null, null, null, null, null},
                {"8.30-9.30", null, null, null, null, null},
                {"9.30-10.30", null, null, null, null, null},
                {"10.30-11.00", "", "IN", "TE", "RV", "AL"},
                {"11.00-12.00", null, null, null, null, null},
                {"12.00-1.00", null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setRowHeight(50);
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selece Class", "A", "B", "C", "D", "E", "F" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Grade", "6", "7", "8", "9", "10", "11" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/image/WhatsApp Image 2017-08-20 at 21.00.30.jpeg"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setText("Time Tabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String clas=jComboBox1.getSelectedItem().toString();
        String grade=jComboBox2.getSelectedItem().toString();
        Connection con = Calendar1.Timetable.dbconnect.connect();
            try{
            String day=null;  
            String subject=null;
            String time=null;
            ResultSet rs;
            PreparedStatement ps;
            
            
            String sql1="select subname,time,day from timetable where class=? and grade=? order by time asc";
            ps=con.prepareStatement(sql1);
            ps.setString(1, clas);
            ps.setString(2, grade);           
            rs=ps.executeQuery();
            
            
            while(rs.next()){
                
                subject= rs.getString("subname");
                time=rs.getString("time");
                day= rs.getString("day");
               // jTable1.setValueAt(time, i, 0);
                 
                if(day.equals("Monday")&& time.equals("7.30")) 
                        jTable1.setValueAt(subject, 0, 1);
                if(day.equals("Monday")&& time.equals("8.30")) 
                        jTable1.setValueAt(subject, 1, 1);
                if(day.equals("Monday")&& time.equals("9.30")) 
                        jTable1.setValueAt(subject, 2, 1);
                if(day.equals("Monday")&& time.equals("11.30")) 
                        jTable1.setValueAt(subject, 4, 1);
                if(day.equals("Monday")&& time.equals("12.30")) 
                        jTable1.setValueAt(subject, 5, 1);
            
            if(day.equals("Tuesday")&& time.equals("7.30")) 
                        jTable1.setValueAt(subject, 0, 2);
                if(day.equals("Tuesday")&& time.equals("8.30")) 
                        jTable1.setValueAt(subject, 1, 2);
                if(day.equals("Tuesday")&& time.equals("9.30")) 
                        jTable1.setValueAt(subject, 2, 2);
                if(day.equals("Tuesday")&& time.equals("11.30")) 
                        jTable1.setValueAt(subject, 4, 2);
                if(day.equals("Tuesday")&& time.equals("12.30")) 
                        jTable1.setValueAt(subject, 5, 2);
           
                if(day.equals("Wednesday")&& time.equals("7.30")) 
                        jTable1.setValueAt(subject, 0, 3);
                if(day.equals("Wednesday")&& time.equals("8.30")) 
                        jTable1.setValueAt(subject, 1, 3);
                if(day.equals("Wednesday")&& time.equals("9.30")) 
                        jTable1.setValueAt(subject, 2, 3);
                if(day.equals("Wednesday")&& time.equals("11.30")) 
                        jTable1.setValueAt(subject, 4, 3);
                if(day.equals("Wednesday")&& time.equals("12.30")) 
                        jTable1.setValueAt(subject, 5, 3);
                
                 if(day.equals("Thursday")&& time.equals("7.30")) 
                        jTable1.setValueAt(subject, 0, 4);
                if(day.equals("Thursday")&& time.equals("8.30")) 
                        jTable1.setValueAt(subject, 1, 4);
                if(day.equals("Thursday")&& time.equals("9.30")) 
                        jTable1.setValueAt(subject, 2, 4);
                if(day.equals("Thursday")&& time.equals("11.30")) 
                        jTable1.setValueAt(subject, 4, 4);
                if(day.equals("Thursday")&& time.equals("12.30")) 
                        jTable1.setValueAt(subject, 5, 4);
               
               if(day.equals("Friday")&& time.equals("7.30")) 
                        jTable1.setValueAt(subject, 0, 5);
                if(day.equals("Friday")&& time.equals("8.30")) 
                        jTable1.setValueAt(subject, 1, 5);
                if(day.equals("Friday")&& time.equals("9.30")) 
                        jTable1.setValueAt(subject, 2, 5);
                if(day.equals("Friday")&& time.equals("11.30")) 
                        jTable1.setValueAt(subject, 4, 5);
                if(day.equals("Friday")&& time.equals("12.30")) 
                        jTable1.setValueAt(subject, 5, 5);
               
        }
            }
        catch(Exception e){
        
            System.out.println(""+e);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //new Profile.
        this.dispose();
        new Profile.MainInterface.Main().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timetableStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timetableStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timetableStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timetableStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timetableStu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
